# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: "engine"

steps:
- task: TerraformTaskV4@4
  displayName: "terraform init"
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Azure subscription 1(42ff5256-95a4-4525-96ff-ee40aa6fd277)'
    backendAzureRmResourceGroupName: 'grp'
    backendAzureRmStorageAccountName: 'vaullerey'
    backendAzureRmContainerName: 'blob'
    backendAzureRmKey: 'prod.terraform.tfstate'
- task: TerraformTaskV4@4
  displayName: 'terraform validate'
  inputs:
    provider: 'azurerm'
    command: 'validate'
- task: TerraformTaskV4@4
  displayName: "terraform plan"
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'Azure subscription 1(42ff5256-95a4-4525-96ff-ee40aa6fd277)'
- task: TerraformTaskV4@4
  displayName: "terraform apply"
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: '-auto-approve'
    environmentServiceNameAzureRM: 'Azure subscription 1(42ff5256-95a4-4525-96ff-ee40aa6fd277)'